window.savedFilters    = null;
window.openFilters     = null;
window.myViewer     = null;
window.bookmarkName = 'mytable';
window.columnNames  = new Array();
window.reportDesign = '';
window.dialogOpen   = null;
window.dialogSave   = null;
window.dialogHelp   = null;
window.savedFiltersGroup = null;
window.resturl         = 'http://ihub.demoimage.com:8000/api/v2/login';
window.restuser        = 'Administrator';
window.restpass        = '';
window.filtersurl      = 'http://ihub.demoimage.com:8000/api/v2/files/620200000100/download?base64=false';
window.savedFiltersTemplate = null;
//window.filters         = {};
window.filesurl        = 'http://ihub.demoimage.com:8000/api/v2/files';